### ISSUE TITLE
Correção Especificação dos Casos de Uso - CSU01 - Inserir dinheiro

### ISSUE THREAD

**Issue by AnaJessicaSS** [EduardoAVicente/Source-Code-Inspection#1]
Na documentação no sumario do primeiro caso de uso está faltando especificar os tipos aceitos

![image](https://github.com/user-attachments/assets/a14e6cc2-632a-4fe3-badd-dfdba01d99b0)

**Comment by EduardoAVicente** [comment]
Correção realizada com sucesso como pdoe ser observada na [wiki](https://github.com/EduardoAVicente/Source-Code-Inspection/wiki)

![image](https://github.com/user-attachments/assets/38c9a927-2b1f-411e-94b6-5e75e2dad11c)
