### ISSUE TITLE
Correção condicional - linha 61

### ISSUE THREAD

**Issue by AnaJessicaSS** [EduardoAVicente/Source-Code-Inspection#10]
O valor de i sempre vai atender o parâmetro de ser maior ou igual a 0, revisar condicional.

https://github.com/EduardoAVicente/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/Troco.java#L61

**Comment by EduardoAVicente** [comment]
Esta issue já foi solucionada na [issue #12](https://github.com/EduardoAVicente/Source-Code-Inspection/issues/12) e ja foi realizado o marge na master atraves da [pull request #28 ](https://github.com/EduardoAVicente/Source-Code-Inspection/pull/28)
