### ISSUE TITLE
Correção condicional - linha 72

### ISSUE THREAD

**Issue by AnaJessicaSS** [EduardoAVicente/Source-Code-Inspection#11]
O valor de i sempre vai atender o parâmetro de ser maior ou igual a 0, revisar condicional.

https://github.com/EduardoAVicente/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/Troco.java#L72

**Comment by EduardoAVicente** [comment]
Esta issue já foi solucionada na i[ssue #13](https://github.com/EduardoAVicente/Source-Code-Inspection/issues/13) e ja foi realizado o marge na master atraves da [pull request #25](https://github.com/EduardoAVicente/Source-Code-Inspection/pull/25)
