### ISSUE TITLE
Correção loops - Linha 13

### ISSUE THREAD

**Issue by EduardoAVicente** [EduardoAVicente/Source-Code-Inspection#14]
Tem muitos loops desnecessários seria melhor substituir por um switch ou algo parecido

https://github.com/EduardoAVicente/Source-Code-Inspection/blob/56b0f5f298c765bf108a41a45cc744f46a5bd433/Source%20Code%20Inspection/src/br/calebe/ticketmachine/core/Troco.java#L13-L45

**Comment by AnaJessicaSS** [comment]
Corrigido durante o ajuste na branche 0.1.8/issue-4-9
