### ISSUE TITLE
Correção Diagrama de Sequência – Solicitar bilhete

### ISSUE THREAD

**Issue by AnaJessicaSS** [EduardoAVicente/Source-Code-Inspection#2]
Está faltando especificar no fluxo onde e quando o sistema verifica o saldo antes de imprimir

![image](https://github.com/user-attachments/assets/18b8081d-f41f-4c5d-b74e-cb60189b41e6)

**Comment by EduardoAVicente** [comment]
Correção no diagrama de sequência – Solicitar bilhete na [wiki](https://github.com/EduardoAVicente/Source-Code-Inspection/wiki#24-diagrama-de-sequ%C3%AAncia--solicitar-bilhete) realizado com sucesso

![image](https://github.com/user-attachments/assets/7bb2f8fc-ebed-40a1-a9d9-ef002d011ace)
