### ISSUE TITLE
Correção diagrama de Classes de interação - Saldo

### ISSUE THREAD

**Issue by EduardoAVicente** [EduardoAVicente/Source-Code-Inspection#3]
A função referente ao saldo está ausente

![image](https://github.com/user-attachments/assets/aabfc3ad-43e3-4df2-8219-705ea969b0c2)

**Comment by AnaJessicaSS** [comment]
Correção no diagrama de Classes de interação na [wiki](https://github.com/EduardoAVicente/Source-Code-Inspection/wiki#24-diagrama-de-sequ%C3%AAncia--solicitar-bilhete) realizado com sucesso

![DiagramaClassesInteração](https://github.com/user-attachments/assets/17b03b76-4762-4b03-be3f-3d73559b4b5d)
